# Filebeat Configuration

# Output to Logstash
output.logstash:
  hosts: ["192.168.1.49:5044"]  # Your Logstash host IP and port

# Logging Configuration
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat.log
  keepfiles: 7
  permissions: 0644

# Enable Filebeat system module for SSH logs
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml

# Ensure system module is enabled for SSH logs
filebeat.modules:
  - module: system
    auth:
      enabled: true
      var.paths: ["/var/log/auth.log"]
